<?php
require_once __DIR__ . '/../config/cors.php';
require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/../middleware/auth.php';
$user=requireRole(['Admin','Teacher']);$db=getDB();$method=$_SERVER['REQUEST_METHOD'];
function sbaTeacher(PDO $db,array $u):int{$s=$db->prepare("SELECT id FROM staff WHERE category='Teaching' AND (user_id=? OR LOWER(email)=LOWER(?) OR LOWER(name)=LOWER(?)) ORDER BY user_id=? DESC LIMIT 1");$s->execute([$u['id'],$u['email']??'',$u['name']??'',$u['id']]);return(int)($s->fetchColumn()?:0);}
$teacherId=($user['role']??'')==='Teacher'?sbaTeacher($db,$user):0;if(($user['role']??'')==='Teacher'&&!$teacherId)jsonResponse(['success'=>false,'message'=>'Teacher profile is not linked'],403);
if($method==='GET'){$sql="SELECT a.*,sub.name subject,c.name class_name,(SELECT COUNT(*) FROM sba_scores x WHERE x.assessment_id=a.id) score_count,ROUND((SELECT AVG(x.score) FROM sba_scores x WHERE x.assessment_id=a.id),2) average_score FROM sba_assessments a JOIN subjects sub ON sub.id=a.subject_id JOIN classes c ON c.id=a.class_id";$p=[];if($teacherId){$sql.=' WHERE a.teacher_id=?';$p[]=$teacherId;}$sql.=' ORDER BY a.updated_at DESC';$q=$db->prepare($sql);$q->execute($p);jsonResponse(['success'=>true,'data'=>$q->fetchAll()]);}
if($method==='POST'){$b=getRequestBody();$classId=(int)($b['class_id']??0);$subjectId=(int)($b['subject_id']??0);$scores=$b['scores']??[];if(!$classId||!$subjectId||empty(trim($b['title']??''))||empty($b['term'])||empty($b['academic_year']))jsonResponse(['success'=>false,'message'=>'Title, subject, class, term and academic year are required'],422);if($teacherId){$q=$db->prepare('SELECT COUNT(*) FROM subjects WHERE id=? AND class_id=? AND teacher_id=?');$q->execute([$subjectId,$classId,$teacherId]);if(!(int)$q->fetchColumn())jsonResponse(['success'=>false,'message'=>'Subject and class must be assigned to you'],403);}$owner=$teacherId?: (int)($b['teacher_id']??0);$max=max(1,(float)($b['max_score']??50));$status=in_array($b['status']??'Draft',['Draft','Submitted'],true)?$b['status']:'Draft';$db->beginTransaction();try{$q=$db->prepare('INSERT INTO sba_assessments (teacher_id,subject_id,class_id,title,assessment_type,max_score,term,academic_year,status) VALUES (?,?,?,?,?,?,?,?,?)');$q->execute([$owner,$subjectId,$classId,htmlspecialchars(trim($b['title']),ENT_QUOTES),htmlspecialchars(trim($b['assessment_type']??'Assessment'),ENT_QUOTES),$max,$b['term'],$b['academic_year'],$status]);$id=(int)$db->lastInsertId();$ins=$db->prepare('INSERT INTO sba_scores (assessment_id,student_id,score,remarks) SELECT ?,s.id,?,? FROM students s WHERE s.id=? AND s.class_id=? AND s.status=\'Active\'');foreach($scores as $row){$score=max(0,min($max,(float)($row['score']??0)));$ins->execute([$id,$score,$row['remarks']??null,(int)($row['student_id']??0),$classId]);}$db->commit();jsonResponse(['success'=>true,'message'=>'SBA assessment saved','id'=>$id],201);}catch(Throwable $e){if($db->inTransaction())$db->rollBack();jsonResponse(['success'=>false,'message'=>'SBA assessment could not be saved'],500);}}
if($method==='DELETE'){$id=(int)($_GET['id']??0);if(!$id)jsonResponse(['success'=>false,'message'=>'Assessment ID required'],422);$sql='DELETE FROM sba_assessments WHERE id=?';$p=[$id];if($teacherId){$sql.=' AND teacher_id=?';$p[]=$teacherId;}$q=$db->prepare($sql);$q->execute($p);if(!$q->rowCount())jsonResponse(['success'=>false,'message'=>'Assessment not found'],404);jsonResponse(['success'=>true,'message'=>'Assessment deleted']);}
jsonResponse(['success'=>false,'message'=>'Method not allowed'],405);
